# public/admin/config.yml
backend:
  name: github
  repo: your-github-username/your-repo-name
  branch: main

local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

i18n:
  # 利用するロケール一覧
  locales:
    - code: 'ja'
      name: '日本語'
  # デフォルトを日本語に
  defaultLocale: 'ja'

collections:
  - name: "skills"
    label: "スキル検証記事"
    folder: "content/skills"
    create: true
    slug: "{{slug}}"
    i18n: true    # このコレクションもローカライズの対象に
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "日付",     name: "date",  widget: "datetime" }
      - { label: "本文",     name: "body",  widget: "markdown" }
